// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVSW0QPXZke7UumUYRLOhj-qFLH65FYc',
    appId: '1:135320514243:web:7cb4e7fd1aa6f009767c76',
    messagingSenderId: '135320514243',
    projectId: 'van-pro-novo',
    authDomain: 'van-pro-novo.firebaseapp.com',
    storageBucket: 'van-pro-novo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4-FY5QP4ZdK6NW36BY9FylRsue35nnU',
    appId: '1:135320514243:android:d804e00bf882a9f9767c76',
    messagingSenderId: '135320514243',
    projectId: 'van-pro-novo',
    storageBucket: 'van-pro-novo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_Ng4ifeb4ZsOJBp_g8u1quBp-FGpxE8',
    appId: '1:135320514243:ios:2a533d7dfc2abff7767c76',
    messagingSenderId: '135320514243',
    projectId: 'van-pro-novo',
    storageBucket: 'van-pro-novo.firebasestorage.app',
    iosBundleId: 'com.example.vanProNovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_Ng4ifeb4ZsOJBp_g8u1quBp-FGpxE8',
    appId: '1:135320514243:ios:2a533d7dfc2abff7767c76',
    messagingSenderId: '135320514243',
    projectId: 'van-pro-novo',
    storageBucket: 'van-pro-novo.firebasestorage.app',
    iosBundleId: 'com.example.vanProNovo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoVSW0QPXZke7UumUYRLOhj-qFLH65FYc',
    appId: '1:135320514243:web:6eb52d3d9d0cafa3767c76',
    messagingSenderId: '135320514243',
    projectId: 'van-pro-novo',
    authDomain: 'van-pro-novo.firebaseapp.com',
    storageBucket: 'van-pro-novo.firebasestorage.app',
  );

}